export const translations = {
  en: {
    nav: { home: "Home", products: "Products", about: "About", support: "Support", searchPlaceholder: "Search products...", wishlist: "Wishlist", cart: "Shopping Cart" },
    announcement: { text: "Crazy Sale - 70% discount on all products! Limited time offer." },
    languageModal: { title: "Where do you live?", subtitle: "Choose your language" },
    home: { newArrival: "NEW ARRIVAL", shopNow: "Shop Now", orderDiscount: "Order now and get a 70% discount", freeShipping: "Free Shipping", freeShippingDesc: "Free shipping on all orders", easyPayment: "Easy Payment", easyPaymentDesc: "Safe and secure payment", easyReturn: "Easy Return", easyReturnDesc: "14 days return policy", support24: "24/7 Support", support24Desc: "Support available all day", featuredProducts: "Featured Products", featuredProductsSubtitle: "Check out our most popular items", viewAll: "View All Products", specialOffer: "Special Offer", specialOfferTitle: "Get Up to 30% Off", specialOfferDesc: "Limited time offer on selected items", shopNowBtn: "Shop Now", testimonials: "Customer Reviews", newsletter: "Subscribe to Our Newsletter", newsletterDesc: "Get 10% off your first order and stay updated with the latest deals", newsletterPlaceholder: "Enter your email address", newsletterSubscribe: "Subscribe", newsletterPrivacy: "We respect your privacy. Unsubscribe at any time." },
    products: { header: "Products", productsFound: "products found", sortBy: "Sort by:", featured: "Featured", priceLow: "Price: Low to High", priceHigh: "Price: High to Low", nameAZ: "Name: A to Z", filterBy: "Filter by", categories: "Categories", priceRange: "Price Range", minPrice: "Min Price", maxPrice: "Max Price", apply: "Apply", addToCart: "Add to Cart", view: "View", addToWishlist: "Add to Wishlist", inWishlist: "In Wishlist", sale: "Sale", new: "New" },
    cart: { title: "Shopping Cart", subtitle: "You have {count} item in your cart", subtitlePlural: "You have {count} items in your cart", empty: "Your cart is empty", emptyDesc: "Looks like you haven't added anything to your cart yet.", continueShopping: "Continue Shopping", items: "Items", remove: "Remove", subtotal: "Subtotal", discount: "Discount (30%)", total: "Total", checkout: "Proceed to Checkout" },
    wishlist: { title: "Wishlist", subtitle: "You have {count} item in your wishlist", subtitlePlural: "You have {count} items in your wishlist", empty: "Your Wishlist is Empty", emptyDesc: "You haven't added any items to your wishlist yet.", continueShopping: "Continue Shopping", totalItems: "Total Items", removeFromWishlist: "Remove from Wishlist" },
    checkout: { title: "Checkout", subtitle: "Please fill in your delivery information", contactInfo: "Contact Information", shippingDetails: "Shipping Details", email: "E-Mail", firstName: "First Name", lastName: "Last Name", streetAddress: "Street Address", addressLine1: "Address Line 1", addressLine2: "Address Line 2 (Optional)", city: "City", postcode: "Postcode / ZIP", country: "Country", backToCart: "Back to Cart", proceedToPayment: "Proceed to Payment" },
    payment: { title: "Enter Your Card Details", cardNumber: "Card Number", expiryDate: "Expiry Date", cvv: "CVV", cardholderName: "Cardholder Name", pay: "Pay", smsCheck: "Check the SMS code after payment" },
    footer: { contactUs: "Contact Us", ourServices: "Our Services", quickLinks: "Quick Links", aboutUs: "About Us", returnPolicy: "Return Policy", faq: "FAQ", privacy: "Privacy & Policy", allProducts: "All Products", shoppingCart: "Shopping Cart", rightsReserved: "All rights reserved." }
  },
  pl: {
    nav: { home: "Strona główna", products: "Produkty", about: "O nas", support: "Wsparcie", searchPlaceholder: "Szukaj produktów...", wishlist: "Lista życzeń", cart: "Koszyk" },
    announcement: { text: "Szalona Wyprzedaż - 70% zniżki na wszystkie produkty! Oferta ograniczona czasowo." },
    languageModal: { title: "Gdzie mieszkasz?", subtitle: "Wybierz swój język" },
    home: { newArrival: "NOWOŚĆ", shopNow: "Kup teraz", orderDiscount: "Zamów teraz i otrzymaj 70% zniżki", freeShipping: "Darmowa Dostawa", freeShippingDesc: "Darmowa dostawa na wszystkie zamówienia", easyPayment: "Łatwa Płatność", easyPaymentDesc: "Bezpieczna i bezpieczna płatność", easyReturn: "Łatwy Zwrot", easyReturnDesc: "14-dniowa polityka zwrotów", support24: "Wsparcie 24/7", support24Desc: "Wsparcie dostępne całą dobę", featuredProducts: "Polecane Produkty", featuredProductsSubtitle: "Sprawdź nasze najpopularniejsze produkty", viewAll: "Zobacz wszystkie produkty", specialOffer: "Oferta Specjalna", specialOfferTitle: "Otrzymaj do 30% zniżki", specialOfferDesc: "Oferta ograniczona czasowo na wybrane produkty", shopNowBtn: "Kup teraz", testimonials: "Opinie Klientów", newsletter: "Zapisz się do naszego newslettera", newsletterDesc: "Otrzymaj 10% zniżki na pierwsze zamówienie i bądź na bieżąco z najnowszymi ofertami", newsletterPlaceholder: "Wprowadź swój adres e-mail", newsletterSubscribe: "Zapisz się", newsletterPrivacy: "Szanujemy Twoją prywatność. Możesz zrezygnować w dowolnym momencie." },
    products: { header: "Produkty", productsFound: "produktów znaleziono", sortBy: "Sortuj według:", featured: "Polecane", priceLow: "Cena: od najniższej", priceHigh: "Cena: od najwyższej", nameAZ: "Nazwa: A do Z", filterBy: "Filtruj według", categories: "Kategorie", priceRange: "Zakres cen", minPrice: "Cena minimalna", maxPrice: "Cena maksymalna", apply: "Zastosuj", addToCart: "Dodaj do koszyka", view: "Zobacz", addToWishlist: "Dodaj do listy życzeń", inWishlist: "W liście życzeń", sale: "Wyprzedaż", new: "Nowość" },
    cart: { title: "Koszyk", subtitle: "Masz {count} produkt w koszyku", subtitlePlural: "Masz {count} produktów w koszyku", empty: "Twój koszyk jest pusty", emptyDesc: "Wygląda na to, że nie dodałeś jeszcze nic do koszyka.", continueShopping: "Kontynuuj zakupy", items: "Produkty", remove: "Usuń", subtotal: "Suma częściowa", discount: "Zniżka (30%)", total: "Razem", checkout: "Przejdź do kasy" },
    wishlist: { title: "Lista życzeń", subtitle: "Masz {count} produkt na liście życzeń", subtitlePlural: "Masz {count} produktów na liście życzeń", empty: "Twoja lista życzeń jest pusta", emptyDesc: "Nie dodałeś jeszcze żadnych produktów do swojej listy życzeń.", continueShopping: "Kontynuuj zakupy", totalItems: "Łączna liczba produktów", removeFromWishlist: "Usuń z listy życzeń" },
    checkout: { title: "Kasa", subtitle: "Proszę wypełnić informacje o dostawie", contactInfo: "Informacje kontaktowe", shippingDetails: "Szczegóły dostawy", email: "E-mail", firstName: "Imię", lastName: "Nazwisko", streetAddress: "Adres ulicy", addressLine1: "Adres linia 1", addressLine2: "Adres linia 2 (opcjonalnie)", city: "Miasto", postcode: "Kod pocztowy", country: "Kraj", backToCart: "Wróć do koszyka", proceedToPayment: "Przejdź do płatności" },
    payment: { title: "Wprowadź dane karty", cardNumber: "Numer karty", expiryDate: "Data ważności", cvv: "CVV", cardholderName: "Imię i nazwisko posiadacza karty", pay: "Zapłać", smsCheck: "Sprawdź kod SMS po płatności" },
    footer: { contactUs: "Skontaktuj się z nami", ourServices: "Nasze usługi", quickLinks: "Szybkie linki", aboutUs: "O nas", returnPolicy: "Polityka zwrotów", faq: "FAQ", privacy: "Prywatność i polityka", allProducts: "Wszystkie produkty", shoppingCart: "Koszyk", rightsReserved: "Wszelkie prawa zastrzeżone." }
  },
  pt: {
    nav: { home: "Início", products: "Produtos", about: "Sobre", support: "Suporte", searchPlaceholder: "Pesquisar produtos...", wishlist: "Lista de desejos", cart: "Carrinho" },
    announcement: { text: "Promoção Incrível - 70% de desconto em todos os produtos! Oferta por tempo limitado." },
    languageModal: { title: "Onde você mora?", subtitle: "Escolha seu idioma" },
    home: { newArrival: "NOVO LANÇAMENTO", shopNow: "Comprar agora", orderDiscount: "Encomende agora e obtenha 70% de desconto", freeShipping: "Envio Grátis", freeShippingDesc: "Envio grátis em todas as encomendas", easyPayment: "Pagamento Fácil", easyPaymentDesc: "Pagamento seguro e protegido", easyReturn: "Devolução Fácil", easyReturnDesc: "Política de devolução de 14 dias", support24: "Suporte 24/7", support24Desc: "Suporte disponível o dia todo", featuredProducts: "Produtos em Destaque", featuredProductsSubtitle: "Confira nossos itens mais populares", viewAll: "Ver todos os produtos", specialOffer: "Oferta Especial", specialOfferTitle: "Obtenha até 30% de desconto", specialOfferDesc: "Oferta por tempo limitado em itens selecionados", shopNowBtn: "Comprar agora", testimonials: "Avaliações de Clientes", newsletter: "Assine nossa newsletter", newsletterDesc: "Obtenha 10% de desconto em seu primeiro pedido e fique atualizado com as últimas ofertas", newsletterPlaceholder: "Digite seu endereço de e-mail", newsletterSubscribe: "Assinar", newsletterPrivacy: "Respeitamos sua privacidade. Cancele a assinatura a qualquer momento." },
    products: { header: "Produtos", productsFound: "produtos encontrados", sortBy: "Ordenar por:", featured: "Em destaque", priceLow: "Preço: menor para maior", priceHigh: "Preço: maior para menor", nameAZ: "Nome: A a Z", filterBy: "Filtrar por", categories: "Categorias", priceRange: "Faixa de preço", minPrice: "Preço mínimo", maxPrice: "Preço máximo", apply: "Aplicar", addToCart: "Adicionar ao carrinho", view: "Ver", addToWishlist: "Adicionar à lista de desejos", inWishlist: "Na lista de desejos", sale: "Promoção", new: "Novo" },
    cart: { title: "Carrinho de Compras", subtitle: "Você tem {count} item no carrinho", subtitlePlural: "Você tem {count} itens no carrinho", empty: "Seu carrinho está vazio", emptyDesc: "Parece que você ainda não adicionou nada ao carrinho.", continueShopping: "Continuar comprando", items: "Itens", remove: "Remover", subtotal: "Subtotal", discount: "Desconto (30%)", total: "Total", checkout: "Prosseguir para o checkout" },
    wishlist: { title: "Lista de Desejos", subtitle: "Você tem {count} item na lista de desejos", subtitlePlural: "Você tem {count} itens na lista de desejos", empty: "Sua lista de desejos está vazia", emptyDesc: "Você ainda não adicionou nenhum item à sua lista de desejos.", continueShopping: "Continuar comprando", totalItems: "Total de itens", removeFromWishlist: "Remover da lista de desejos" },
    checkout: { title: "Checkout", subtitle: "Por favor, preencha suas informações de entrega", contactInfo: "Informações de contato", shippingDetails: "Detalhes de envio", email: "E-mail", firstName: "Primeiro nome", lastName: "Sobrenome", streetAddress: "Endereço", addressLine1: "Linha de endereço 1", addressLine2: "Linha de endereço 2 (opcional)", city: "Cidade", postcode: "Código postal", country: "País", backToCart: "Voltar ao carrinho", proceedToPayment: "Prosseguir para o pagamento" },
    payment: { title: "Digite os dados do cartão", cardNumber: "Número do cartão", expiryDate: "Data de validade", cvv: "CVV", cardholderName: "Nome do portador do cartão", pay: "Pagar", smsCheck: "Verifique o código SMS após o pagamento" },
    footer: { contactUs: "Entre em contato", ourServices: "Nossos serviços", quickLinks: "Links rápidos", aboutUs: "Sobre nós", returnPolicy: "Política de devolução", faq: "FAQ", privacy: "Privacidade e política", allProducts: "Todos os produtos", shoppingCart: "Carrinho de compras", rightsReserved: "Todos os direitos reservados." }
  },
  he: {
    nav: { home: "בית", products: "מוצרים", about: "אודות", support: "תמיכה", searchPlaceholder: "חפש מוצרים...", wishlist: "רשימת משאלות", cart: "עגלת קניות" },
    announcement: { text: "מבצע מטורף - 70% הנחה על כל המוצרים! הצעה מוגבלת בזמן." },
    languageModal: { title: "איפה אתה גר?", subtitle: "בחר את השפה שלך" },
    home: { newArrival: "חדש", shopNow: "קנה עכשיו", orderDiscount: "הזמן עכשיו וקבל 70% הנחה", freeShipping: "משלוח חינם", freeShippingDesc: "משלוח חינם על כל ההזמנות", easyPayment: "תשלום קל", easyPaymentDesc: "תשלום בטוח ומאובטח", easyReturn: "החזרה קלה", easyReturnDesc: "מדיניות החזרה של 14 יום", support24: "תמיכה 24/7", support24Desc: "תמיכה זמינה כל היום", featuredProducts: "מוצרים מומלצים", featuredProductsSubtitle: "עיין בפריטים הפופולריים ביותר שלנו", viewAll: "צפה בכל המוצרים", specialOffer: "הצעה מיוחדת", specialOfferTitle: "קבל עד 30% הנחה", specialOfferDesc: "הצעה מוגבלת בזמן על פריטים נבחרים", shopNowBtn: "קנה עכשיו", testimonials: "ביקורות לקוחות", newsletter: "הירשם לניוזלטר שלנו", newsletterDesc: "קבל 10% הנחה על ההזמנה הראשונה שלך והישאר מעודכן עם ההצעות האחרונות", newsletterPlaceholder: "הזן את כתובת הדוא\"ל שלך", newsletterSubscribe: "הירשם", newsletterPrivacy: "אנו מכבדים את הפרטיות שלך. ניתן לבטל את המנוי בכל עת." },
    products: { header: "מוצרים", productsFound: "מוצרים נמצאו", sortBy: "מיין לפי:", featured: "מומלץ", priceLow: "מחיר: נמוך לגבוה", priceHigh: "מחיר: גבוה לנמוך", nameAZ: "שם: א' עד ת'", filterBy: "סנן לפי", categories: "קטגוריות", priceRange: "טווח מחירים", minPrice: "מחיר מינימלי", maxPrice: "מחיר מקסימלי", apply: "החל", addToCart: "הוסף לעגלה", view: "צפה", addToWishlist: "הוסף לרשימת משאלות", inWishlist: "ברשימת משאלות", sale: "מבצע", new: "חדש" },
    cart: { title: "עגלת קניות", subtitle: "יש לך {count} פריט בעגלה", subtitlePlural: "יש לך {count} פריטים בעגלה", empty: "העגלה שלך ריקה", emptyDesc: "נראה שלא הוספת עדיין כלום לעגלה.", continueShopping: "המשך קניות", items: "פריטים", remove: "הסר", subtotal: "סיכום ביניים", discount: "הנחה (30%)", total: "סה\"כ", checkout: "המשך לקופה" },
    wishlist: { title: "רשימת משאלות", subtitle: "יש לך {count} פריט ברשימת משאלות", subtitlePlural: "יש לך {count} פריטים ברשימת משאלות", empty: "רשימת המשאלות שלך ריקה", emptyDesc: "עדיין לא הוספת פריטים לרשימת המשאלות שלך.", continueShopping: "המשך קניות", totalItems: "סה\"כ פריטים", removeFromWishlist: "הסר מרשימת משאלות" },
    checkout: { title: "קופה", subtitle: "אנא מלא את פרטי המשלוח שלך", contactInfo: "פרטי קשר", shippingDetails: "פרטי משלוח", email: "דוא\"ל", firstName: "שם פרטי", lastName: "שם משפחה", streetAddress: "כתובת רחוב", addressLine1: "שורת כתובת 1", addressLine2: "שורת כתובת 2 (אופציונלי)", city: "עיר", postcode: "מיקוד", country: "מדינה", backToCart: "חזור לעגלה", proceedToPayment: "המשך לתשלום" },
    payment: { title: "הזן את פרטי הכרטיס", cardNumber: "מספר כרטיס", expiryDate: "תאריך תפוגה", cvv: "CVV", cardholderName: "שם בעל הכרטיס", pay: "שלם", smsCheck: "בדוק את קוד ה-SMS לאחר התשלום" },
    footer: { contactUs: "צור קשר", ourServices: "השירותים שלנו", quickLinks: "קישורים מהירים", aboutUs: "אודותינו", returnPolicy: "מדיניות החזרה", faq: "שאלות נפוצות", privacy: "פרטיות ומדיניות", allProducts: "כל המוצרים", shoppingCart: "עגלת קניות", rightsReserved: "כל הזכויות שמורות." }
  },
  el: {
    nav: { home: "Αρχική", products: "Προϊόντα", about: "Σχετικά", support: "Υποστήριξη", searchPlaceholder: "Αναζήτηση προϊόντων...", wishlist: "Λίστα επιθυμιών", cart: "Καλάθι" },
    announcement: { text: "Τρελή Προσφορά - 70% έκπτωση σε όλα τα προϊόντα! Προσφορά περιορισμένου χρόνου." },
    languageModal: { title: "Πού μένετε;", subtitle: "Επιλέξτε τη γλώσσα σας" },
    home: { newArrival: "ΝΕΑ ΑΦΙΞΗ", shopNow: "Αγοράστε τώρα", orderDiscount: "Παραγγείλετε τώρα και λάβετε 70% έκπτωση", freeShipping: "Δωρεάν Αποστολή", freeShippingDesc: "Δωρεάν αποστολή σε όλες τις παραγγελίες", easyPayment: "Εύκολη Πληρωμή", easyPaymentDesc: "Ασφαλής και προστατευμένη πληρωμή", easyReturn: "Εύκολη Επιστροφή", easyReturnDesc: "Πολιτική επιστροφής 14 ημερών", support24: "Υποστήριξη 24/7", support24Desc: "Υποστήριξη διαθέσιμη όλη την ημέρα", featuredProducts: "Προτεινόμενα Προϊόντα", featuredProductsSubtitle: "Δείτε τα πιο δημοφιλή προϊόντα μας", viewAll: "Δείτε όλα τα προϊόντα", specialOffer: "Ειδική Προσφορά", specialOfferTitle: "Λάβετε έως 30% έκπτωση", specialOfferDesc: "Προσφορά περιορισμένου χρόνου σε επιλεγμένα προϊόντα", shopNowBtn: "Αγοράστε τώρα", testimonials: "Αξιολογήσεις Πελατών", newsletter: "Εγγραφείτε στο ενημερωτικό δελτίο μας", newsletterDesc: "Λάβετε 10% έκπτωση στην πρώτη σας παραγγελία και μείνετε ενημερωμένοι με τις τελευταίες προσφορές", newsletterPlaceholder: "Εισάγετε τη διεύθυνση email σας", newsletterSubscribe: "Εγγραφή", newsletterPrivacy: "Σεβόμαστε την ιδιωτικότητά σας. Μπορείτε να διαγραφείτε ανά πάσα στιγμή." },
    products: { header: "Προϊόντα", productsFound: "προϊόντα βρέθηκαν", sortBy: "Ταξινόμηση κατά:", featured: "Προτεινόμενο", priceLow: "Τιμή: Χαμηλή προς Υψηλή", priceHigh: "Τιμή: Υψηλή προς Χαμηλή", nameAZ: "Όνομα: Α έως Ω", filterBy: "Φιλτράρισμα κατά", categories: "Κατηγορίες", priceRange: "Εύρος τιμών", minPrice: "Ελάχιστη τιμή", maxPrice: "Μέγιστη τιμή", apply: "Εφαρμογή", addToCart: "Προσθήκη στο καλάθι", view: "Προβολή", addToWishlist: "Προσθήκη στη λίστα επιθυμιών", inWishlist: "Στη λίστα επιθυμιών", sale: "Προσφορά", new: "Νέο" },
    cart: { title: "Καλάθι Αγορών", subtitle: "Έχετε {count} προϊόν στο καλάθι", subtitlePlural: "Έχετε {count} προϊόντα στο καλάθι", empty: "Το καλάθι σας είναι άδειο", emptyDesc: "Φαίνεται ότι δεν έχετε προσθέσει ακόμα τίποτα στο καλάθι.", continueShopping: "Συνέχεια αγορών", items: "Προϊόντα", remove: "Αφαίρεση", subtotal: "Υποσύνολο", discount: "Έκπτωση (30%)", total: "Σύνολο", checkout: "Συνέχεια στο ταμείο" },
    wishlist: { title: "Λίστα Επιθυμιών", subtitle: "Έχετε {count} προϊόν στη λίστα επιθυμιών", subtitlePlural: "Έχετε {count} προϊόντα στη λίστα επιθυμιών", empty: "Η λίστα επιθυμιών σας είναι άδεια", emptyDesc: "Δεν έχετε προσθέσει ακόμα προϊόντα στη λίστα επιθυμιών σας.", continueShopping: "Συνέχεια αγορών", totalItems: "Συνολικός αριθμός προϊόντων", removeFromWishlist: "Αφαίρεση από τη λίστα επιθυμιών" },
    checkout: { title: "Ταμείο", subtitle: "Παρακαλώ συμπληρώστε τα στοιχεία παράδοσης", contactInfo: "Στοιχεία επικοινωνίας", shippingDetails: "Λεπτομέρειες αποστολής", email: "Email", firstName: "Όνομα", lastName: "Επώνυμο", streetAddress: "Διεύθυνση", addressLine1: "Γραμμή διεύθυνσης 1", addressLine2: "Γραμμή διεύθυνσης 2 (προαιρετικό)", city: "Πόλη", postcode: "Ταχυδρομικός κώδικας", country: "Χώρα", backToCart: "Επιστροφή στο καλάθι", proceedToPayment: "Συνέχεια στην πληρωμή" },
    payment: { title: "Εισαγάγετε τα στοιχεία της κάρτας", cardNumber: "Αριθμός κάρτας", expiryDate: "Ημερομηνία λήξης", cvv: "CVV", cardholderName: "Όνομα κατόχου κάρτας", pay: "Πληρωμή", smsCheck: "Ελέγξτε τον κωδικό SMS μετά την πληρωμή" },
    footer: { contactUs: "Επικοινωνήστε μαζί μας", ourServices: "Οι υπηρεσίες μας", quickLinks: "Γρήγοροι σύνδεσμοι", aboutUs: "Σχετικά με εμάς", returnPolicy: "Πολιτική επιστροφής", faq: "Συχνές ερωτήσεις", privacy: "Απόρρητο και πολιτική", allProducts: "Όλα τα προϊόντα", shoppingCart: "Καλάθι αγορών", rightsReserved: "Όλα τα δικαιώματα κατοχυρωμένα." }
  }
};

export const t = (key, language = 'en', params = {}) => {
  const keys = key.split('.');
  let value = translations[language] || translations.en;
  
  for (const k of keys) {
    if (value && value[k]) {
      value = value[k];
    } else {
      value = translations.en;
      for (const k2 of keys) {
        value = value[k2];
      }
      break;
    }
  }
  
  if (typeof value !== 'string') {
    return key;
  }
  
  return value.replace(/\{(\w+)\}/g, (match, param) => {
    return params[param] !== undefined ? params[param] : match;
  });
};
